name: Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Clean up dependencies
      run: |
        rm -rf node_modules package-lock.json
    
    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      run: npm test -- --reporter=verbose
      
    - name: Check for test coverage
      run: |
        if [ -f coverage/index.html ]; then
          echo "Test coverage report generated"
        else
          echo "No coverage report found"
        fi 